### ISSUE TITLE
Adding OpenType small caps

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/xits-math#53]
These features are useful if an user want true small caps instead of scaled small caps in the text.

**Comment by KrasnayaPloshchad** [comment]
See also: https://practicaltypography.com/times-new-roman.html

**Comment by callegar** [comment]
Small caps would really be useful because modern TeX engines (luatex/xetex) cannot fake it.

As of today, XITS makes an excellent replacement for Times (STIX Two Text does not seem to be metrically compatible). While TeX Gyre Termes nominally has Small Caps, those are not metric compatible with Times and appear to be more like petite caps.

**Comment by KrasnayaPloshchad** [comment]
> While TeX Gyre Termes nominally has Small Caps, those are not metric compatible with Times and appear to be more like petite caps.

Really? TeX Gyre Termes is derived from Nimbus Roman, which is metric compatible with Times Roman.

**Comment by KrasnayaPloshchad** [comment]
In this presentation, page 37-40 illistrated how does the glyph created.
http://www.gust.org.pl/projects/e-foundry/tex-gyre/afp05.pdf
It would be nice if a PR is submited for this.

**Comment by callegar** [comment]
Those parts of TGT taken from Nimbus Roman are indeed metrically compatible with Times Roman, but Nimbus Roman does not include Small Caps. My suspect that TGT's Small Caps are not compatible with the Times New Roman ones comes from visual comparison (as a matter of fact STIX Two Text Small Caps are more similar to Times Roman ones than those in TGT, because the Small Caps height is way too small). It was then confirmed by the very document you cite (afp05.pdf), which indicates that small caps are mechanically generated from capitals by making their height extactly equal to an x height. For fonts with a relatively low x-height, such as Times Roman, small caps are larger than this, though (up to about 30% larger than x-height, or 70% the height of full capitals — I do not know the exact numbers for Times Roman) and the form where the small capitals have exactly the same height as a small x is generally indicated as Petite Caps.

IMHO, TGT could easily provide both Small and Petite Caps, since this would involve merely changing a scaling factor in an algorithm. It would also be great if XITS could use a similar mechanical transformation to provide Small and Petite Caps, because as said, they cannot be "faked" on LaTeX when using fontspec to take advantage of Unicode and modern font features.

It is unclear to me how bugs should be reported for the TeX Gyre fonts and whether they are developed in the open like XITS. So far I could not find a tracker nor a source for the TeX Gyre Metatype1 code.
